# Generated by Django 3.1.7 on 2021-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=12)),
                ('village', models.TextField(max_length=200)),
                ('region', models.TextField(max_length=200)),
                ('country', models.TextField(max_length=50)),
                ('militants_avg', models.IntegerField()),
                ('unknown_avg', models.IntegerField()),
                ('civilians_avg', models.IntegerField()),
                ('total_avg', models.IntegerField()),
                ('president_name', models.TextField(max_length=20)),
                ('target_organization_name', models.TextField(max_length=50)),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
            ],
        ),
    ]
