# Generated by Django 3.1.7 on 2021-03-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0003_remove_strikesdata_unnamed_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strikesdata',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strikesdata',
            name='geo_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
