# Generated by Django 3.1.7 on 2021-03-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0007_auto_20210314_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presidentdata',
        ),
    ]
