# Generated by Django 3.1.7 on 2021-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0011_auto_20210314_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommanderinChief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.TextField()),
                ('numofstrikes', models.IntegerField()),
                ('yearsinoffice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Presidents',
        ),
    ]
