# Generated by Django 3.1.7 on 2021-03-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0012_auto_20210314_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommanderinChief',
        ),
    ]
