# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0014_commanderinchief'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikesByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(max_length=4)),
                ('numofstrikes', models.IntegerField()),
            ],
        ),
    ]
