# Generated by Django 3.1.7 on 2021-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0016_contributedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributedata',
            name='civilians_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='geo_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='geo_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='militants_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='president_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='region',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='target_organization_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='total_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='unknown_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='village',
            field=models.TextField(),
        ),
    ]
