# Generated by Django 3.1.7 on 2021-03-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0017_auto_20210316_0521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributedata',
        ),
    ]
