# Generated by Django 3.1.7 on 2021-03-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0018_delete_contributedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('village', models.TextField()),
                ('region', models.TextField()),
                ('country', models.TextField()),
                ('militants_avg', models.FloatField()),
                ('unknown_avg', models.FloatField()),
                ('civilians_avg', models.FloatField()),
                ('total_avg', models.FloatField()),
                ('president_name', models.TextField()),
                ('target_organization_name', models.TextField()),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
            ],
        ),
    ]
