# Generated by Django 3.1.7 on 2021-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikesapi', '0020_auto_20210316_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributedata',
            name='civilians_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='militants_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contributedata',
            name='unknown_avg',
            field=models.FloatField(null=True),
        ),
    ]
